[tools]
# renovate: datasource=adoptium-java depName=java
java = "temurin-25.0.3+9.0.LTS"
# renovate: datasource=maven depName=org.apache.maven:apache-maven
maven = "3.9.15"
# renovate: datasource=github-releases depName=nektos/act extractVersion=^v(?<version>.*)$
"aqua:nektos/act" = "0.2.87"
# renovate: datasource=github-releases depName=gitleaks/gitleaks extractVersion=^v(?<version>.*)$
"aqua:gitleaks/gitleaks" = "8.30.1"
# renovate: datasource=github-releases depName=aquasecurity/trivy extractVersion=^v(?<version>.*)$
"aqua:aquasecurity/trivy" = "0.70.0"
