# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download repository
      uses: actions/checkout@v3.0.2

    - name: Set up JDK
      uses: actions/setup-java@v3.3.0
      with:
        java-version: 18
        distribution: 'temurin'
 
    - name: Cache Maven packages
      uses: actions/cache@v3.0.3
      env:
        cache-name: cache-mvn-temurin-18
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
      
    - name: Test with Maven
      run: mvn -B test --file pom.xml
